name: Infisical secrets from environment variables

on:
  push:
  workflow_dispatch:
  workflow_call:
    secrets:
      MACHINE_IDENTITY_CLIENT_ID:
        required: true
      MACHINE_IDENTITY_CLIENT_SECRET:
        required: true
jobs:
  secrets-fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: Infisical/secrets-loader-action@main
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: "dev"
          project-slug: "test-p-vu-r"
          export-type: "env"
          secret-path: "/"
      - run: env
